// app/(protected)/dashboard/notifications/_components/mockNotifications.ts
import { Notification } from '@/types/notification';

export const mockNotifications: Notification[] = [
  {
    id: '1',
    type: 'request',
    title: 'Contract Agreement Request',
    description: 'Sarah Johnson has requested your approval for the Enterprise Software License Agreement.',
    priority: 'high',
    status: 'pending',
    contractName: 'Enterprise Software License Agreement',
    contractId: 'CTR-2024-001',
    sender: 'Sarah Johnson',
    senderAvatar: 'SJ',
    timestamp: '2024-01-07T10:30:00Z',
    isRead: false,
    actions: [
      { label: 'Review', type: 'primary', action: 'review' },
      { label: 'Decline', type: 'destructive', action: 'decline' },
    ],
  },
  {
    id: '2',
    type: 'payment',
    title: 'Payment Due Soon',
    description: 'Payment of $15,000 for the Marketing Services Contract is due in 3 days.',
    priority: 'urgent',
    status: 'pending',
    contractName: 'Marketing Services Contract',
    contractId: 'CTR-2024-002',
    amount: 15000,
    dueDate: '2024-01-10',
    timestamp: '2024-01-07T09:15:00Z',
    isRead: false,
    actions: [
      { label: 'Pay Now', type: 'primary', action: 'pay' },
      { label: 'View Details', type: 'secondary', action: 'view' },
    ],
  },
  {
    id: '3',
    type: 'alert',
    title: 'Contract Expiring Soon',
    description: 'The Annual Maintenance Agreement with TechCorp Inc. expires in 14 days. Consider renewal.',
    priority: 'medium',
    status: 'pending',
    contractName: 'Annual Maintenance Agreement',
    contractId: 'CTR-2023-089',
    dueDate: '2024-01-21',
    timestamp: '2024-01-07T08:00:00Z',
    isRead: true,
    actions: [
      { label: 'Renew', type: 'primary', action: 'renew' },
      { label: 'Archive', type: 'secondary', action: 'archive' },
    ],
  },
  {
    id: '4',
    type: 'update',
    title: 'Contract Approved',
    description: 'The Consulting Services Agreement has been approved by all parties and is now active.',
    priority: 'low',
    status: 'approved',
    contractName: 'Consulting Services Agreement',
    contractId: 'CTR-2024-003',
    sender: 'Legal Department',
    senderAvatar: 'LD',
    timestamp: '2024-01-06T16:45:00Z',
    isRead: true,
    actions: [
      { label: 'View Contract', type: 'primary', action: 'view' },
    ],
  },
  {
    id: '5',
    type: 'payment',
    title: 'Payment Overdue',
    description: 'Payment of $8,500 for the Cloud Infrastructure Contract is 5 days overdue.',
    priority: 'urgent',
    status: 'overdue',
    contractName: 'Cloud Infrastructure Contract',
    contractId: 'CTR-2023-156',
    amount: 8500,
    dueDate: '2024-01-02',
    timestamp: '2024-01-07T07:00:00Z',
    isRead: false,
    actions: [
      { label: 'Pay Now', type: 'primary', action: 'pay' },
      { label: 'Contact Support', type: 'secondary', action: 'support' },
    ],
  },
  {
    id: '6',
    type: 'request',
    title: 'Signature Required',
    description: 'Michael Chen needs your signature on the Non-Disclosure Agreement before the project kickoff.',
    priority: 'high',
    status: 'pending',
    contractName: 'Non-Disclosure Agreement',
    contractId: 'CTR-2024-004',
    sender: 'Michael Chen',
    senderAvatar: 'MC',
    timestamp: '2024-01-06T14:20:00Z',
    isRead: false,
    actions: [
      { label: 'Sign Now', type: 'primary', action: 'sign' },
      { label: 'Request Changes', type: 'secondary', action: 'changes' },
    ],
  },
  {
    id: '7',
    type: 'alert',
    title: 'Compliance Review Required',
    description: 'The Data Processing Agreement requires a quarterly compliance review as per GDPR requirements.',
    priority: 'medium',
    status: 'pending',
    contractName: 'Data Processing Agreement',
    contractId: 'CTR-2023-201',
    timestamp: '2024-01-05T11:30:00Z',
    isRead: true,
    actions: [
      { label: 'Start Review', type: 'primary', action: 'review' },
      { label: 'Schedule Later', type: 'secondary', action: 'schedule' },
    ],
  },
  {
    id: '8',
    type: 'update',
    title: 'Amendment Completed',
    description: 'The amendment to the Partnership Agreement has been executed and filed.',
    priority: 'low',
    status: 'completed',
    contractName: 'Partnership Agreement - Amendment #2',
    contractId: 'CTR-2023-045-A2',
    sender: 'System',
    timestamp: '2024-01-05T09:00:00Z',
    isRead: true,
    actions: [
      { label: 'View Document', type: 'primary', action: 'view' },
    ],
  },
];
